version: "3"

#services:
#
#  mariadb:
#    image: mariadb
#    container_name: my-mariadb-container
#    env_file: .env
#    build:
#      context: requirements/MARIADB
#      args:
##        MYSQL_DATABASE: ${MYSQL_DATABASE}
#        MYSQL_USER: ${MYSQL_USER}
#        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#    hostname: "mariadb"
#    restart: unless-stopped
#    networks:
#      - network
#    volumes:
#      - db:/var/lib/mysql
#    expose:
#      - "3306" # port between db and wordpress
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    networks:
      - your-network-name
    ports:
      - "3306:3306"


#  wordpress:
#    image: wordpress:latest
#    environment:
#      WORDPRESS_DB_HOST: mariadb:3306
#      WORDPRESS_DB_USER: wordpressuser
#      WORDPRESS_DB_PASSWORD: wordpresspassword
#      WORDPRESS_DB_NAME: wordpress
#    ports:
#      - "9000:80"
#    networks:
#      - app-network
#
#  nginx:
#    image: nginx:latest
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    networks:
#      - app-network
