version: "3.9"

networks:
  localhost:
    name: mmensing

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    build: ./requirements/NGINX
    restart: unless-stopped
    env_file: .env
    volumes:
      - wp:/var/www/
    networks:
      - localhost
    ports:
      - "443:443"

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/WORDPRESS
      args:
        - MYSQL_NAME
        - DB_HOST
        - MYSQL_PASSWORD
        - MYSQL_USER
        - DOMAIN_NAME
    restart: unless-stopped
    env_file: .env
    networks:
      - localhost
    volumes:
      - wp:/var/www/

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/MARIADB
      args:
        - MYSQL_NAME
        - DB_HOST
        - MYSQL_PASSWORD
        - MYSQL_USER
        - DOMAIN_NAME
    restart: unless-stopped
    env_file: .env
    networks:
      - localhost
    volumes:
      - db:/var/lib/mysql


volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/MARIADB
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/WORDPRESS
